### ISSUE TITLE
Module not working with nuxt3

### ISSUE THREAD

**Issue by andrei-vintila** [nuxt-community/color-mode-module#110]
### Version
@nuxtjs/color-mode: v2.1.1
nuxt: 3.0.0-27238235.a1bcc53

### Reproduction Link

https://stackblitz.com/edit/nuxt3-color-mode-aehgts?file=nuxt.config.js
### Steps to reproduce
Just add color-mode as buildModule

### What is Expected?
For the module to load

### What is actually happening?
Crashes the whole build, seems like it is related to not using @nuxt/kit

**Comment by iamarpitpatidar** [comment]
yeah its not yet compatible due to the api changes,.

**Comment by brolnickij** [comment]
https://github.com/nuxt-community/color-mode-module/releases/tag/v3.0.0
