### ISSUE TITLE
Ability to change the 'mode' selector

### ISSUE THREAD

**Issue by kn0wn** [nuxt-community/color-mode-module#12]
### Is your feature request related to a problem? Please describe.
N/A

### Describe the solution you'd like
To be able to set the class name of the mode selector. For example: on the add/remove class function, it would be good to be able to set it to `theme-dark` instead of `mode-dark`. 

### Describe alternatives you've considered
N/A

### Additional context
Happy to create a PR if needed.

**Comment by Atinux** [comment]
Hi @kn0wn 

What would be the use case of changing the class actually?

**Comment by danbeneventano** [comment]
Requesting this be reopened - one such use case is with the new dark mode support in TailwindCSS (https://github.com/tailwindlabs/tailwindcss/pull/2279). Tailwind expects the class to just be called "dark"

**Comment by lopis** [comment]
Another use case is simply consistency with the product's design systems. Not everyone calls it "dark mode". Would love to see this option possible.
