### ISSUE TITLE
Creates duplicate of vueUse colorMode

### ISSUE THREAD

**Issue by Aft1n** [nuxt-community/color-mode-module#125]
Hello, im not sure if this is my fault, problem of naming or a bug. 

So when this module was installed after vueUse module, the cli shows me this warning:
<img width="488" alt="cli warning" src="https://user-images.githubusercontent.com/54577662/154591033-a51f3563-3486-40ee-84d6-9b8fe841613d.png">

i have used vueUse colorMode()  composable first, but decided to install this module. So i'm not sure how to get rid of the warning, and if its the problem of naming or maybe i've done something wrong? Thanks

**Comment by ewilan-riviere** [comment]
Same for me!

**Comment by weleo** [comment]
`Disabling duplicate auto import 'useColorMode' (imported from '~/node_modules/@nuxtjs/color-mode/dist/runtime/composables')     `

**Comment by Atinux** [comment]
Should be fixed with latest version of vueuse and nuxt3 😊
