### ISSUE TITLE
Cannot find name '$colorMode'.ts(2304)

### ISSUE THREAD

**Issue by VidarDev** [nuxt-community/color-mode-module#130]
The error still occurs under nuxt 3 & "@nuxtjs/color-mode": "^3.0.1"

Cannot find name '$colorMode'.ts(2304)

I have installed it under dev

**Comment by danielroe** [comment]
I've just published it as `3.0.2`. You should continue to access it as `$colorMode` unless you are using composition API, in which case you will use `const colorMode = useColorMode()` in your setup function. (This is the recommended approach.)

**Comment by VidarDev** [comment]
sorry i am brand new to this story. So I try to use the part below with Tailwind v2

**Comment by danielroe** [comment]
When you tried earlier, I hadn't published it yet. You can try installing 3.0.2. And if you are using it in your template, access it as `$colorMode`.

**Comment by VidarDev** [comment]
Same after update

![package json](https://user-images.githubusercontent.com/98586665/157013721-f7c9dd30-9cf4-42d7-8acf-d0b2171914db.png)
![$colormode](https://user-images.githubusercontent.com/98586665/157013740-7bc57ff6-684a-4d84-a398-9e1786e01cb5.png)

**Comment by danielroe** [comment]
It's working here. If you're still experiencing this after restarting your IDE, would you provide a reproduction?

![CleanShot 2022-03-07 at 10 40 37](https://user-images.githubusercontent.com/28706372/157015866-f924b4ea-439b-4aa5-acdc-1c767e838c46.png)

**Comment by VidarDev** [comment]
I will try, and of course provide a reproduction

**Comment by VidarDev** [comment]
ok it took an IDE restart. Now it works.

Thanks a lot!
