### ISSUE TITLE
Fade Transitions

### ISSUE THREAD

**Issue by jhull** [nuxt-community/color-mode-module#14]
Currently, when in Dark Mode, fades fade out into white and then back to dark. Would be great if it could attend to this and properly switch to "black" when fading in and out.

**Comment by Atinux** [comment]
Not sure to understand the issue, also this module does not do any transitions actually.

Do you have a demo or video of the issue you describe?

**Comment by jhull** [comment]
It could be something totally easy that I've just overlooked, but here's a video of what I'm talking about - prepare your eyes for snowblind mode! 

https://vimeo.com/419165645

**Comment by bdrtsky** [comment]
@jhull Sorry, we couldn’t find that page

**Comment by jhull** [comment]
Sry about that. Was set to private. Should work now.

**Comment by bdrtsky** [comment]
Well...As far as my telepathy skill allow me to suggest what is wrong fromn this video clip, my suggestion is you applying dark background to elements inside `#__nuxt`, so when they are fading your white body is showing. Try to apply this styles to body instead.

**Comment by jhull** [comment]
Well, that was ridiculously simple...

```
.dark-mode #__nuxt {
  @apply bg-grey-950
}
```
