### ISSUE TITLE
Add @types for better typescript support

### ISSUE THREAD

**Issue by xavism** [nuxt-community/color-mode-module#15]
Now Vetur throws an error when accessing this.$colorMode:
```
Property '$colorMode' does not exist on type 'CombinedVueInstance...'
```

A solution could be to define the $colorMode object in @types

**Comment by xavism** [comment]
Maybe creating a ```module.d.ts``` file:
``` typescript
import Vue from 'vue'
declare module 'vue/types/vue' {
  interface VueColorMode extends Vue {
    value: string
    preference: Boolean
    unknown: string
  }
  interface Vue {
    $colorMode: VueColorMode
  }
}
```

**Comment by xavism** [comment]
I tried to make a PR @Atinux but Idk how to add the definition file in the build :(

Thanks in advance

**Comment by Atinux** [comment]
Hey @xavism 

Thank you for your help on this, I think we need to so something similar to https://github.com/nuxt/http/tree/dev/types

And then add the files in the `package.json`, see https://github.com/nuxt/http/blob/dev/package.json#L12

**Comment by jankal** [comment]
@Atinux It doesn't seem this is done yet. It might be a good idea to add the `types` field to `package.json` and reference the type declarations there. I send #52 for this.

**Comment by VidarDev** [comment]
The error still occurs under nuxt 3 & "@nuxtjs/color-mode": "^3.0.1"
