### ISSUE TITLE
Updating to 1.02 throws console error

### ISSUE THREAD

**Issue by eripoll** [nuxt-community/color-mode-module#21]
### Version
@nuxtjs/color-mode: 1.0.2
nuxt: 2.13.3

### Steps to reproduce
I just updated to 1.0.2, with no other change and my app now throws
```
[Vue warn]: data functions should return an object:
https://vuejs.org/v2/guide/components.html#data-Must-Be-a-Function
(found in <Root>)
```

### What is Expected?
No error ;)

Side note: 
Using 1.0.0 with nuxjs 2.13.3 in SPA mode, when generating and starting, I get the following error
```
TypeError: Cannot read property 'preference' of undefined
    at be (app.460976a.js:1)
    at app.460976a.js:1
    at f (vendors~app.23ddfa9.js:2)
    at Generator._invoke (vendors~app.23ddfa9.js:2)
    at Generator.O.forEach.e.<computed> [as next] (vendors~app.23ddfa9.js:2)
    at r (app.c57ce17.js:2)
    at l (app.c57ce17.js:2)
```

**Comment by eripoll** [comment]
Ok so I updated to Nuxtjs 2.14.0 and color 1.0.2
I don't have th warning anymore BUT
yarn build + yarn start as an SPA still throws the same error on start up:

```
TypeError: Cannot read property 'preference' of undefined
    at be (app.250609e.js:1)
    at app.250609e.js:1
    at h (vendors~app.761da66.js:2)
    at Generator._invoke (vendors~app.761da66.js:2)
    at Generator.next (vendors~app.761da66.js:2)
    at r (app.a5226ce.js:2)
    at l (app.a5226ce.js:2)
```

**Comment by rankjie** [comment]
`ctx.nuxtState.colorMode` is `undefined` on my dev environment (macOS 10.15.6, nuxt 2.14.0, SPA mode)
[This commit](https://github.com/nuxt-community/color-mode-module/commit/7a873ab1f6f862b608923e904ae153b8f89864fc) caused the bug and changing themes is not working in 1.0.2.
Revert this part fixed everything for me. https://github.com/nuxt-community/color-mode-module/commit/7a873ab1f6f862b608923e904ae153b8f89864fc#diff-58e6cb97fd6582c2fdc3e79032ce4070L13-L1

**Comment by eripoll** [comment]
@rankjie I applied your patch and I am able to select Theme on 1.02, thanks!

However, when building (yarn build), I still have y app crashing with the 
`Cannot read property 'preference' of undefined`
error.

Do you see the same issue? Any idea ono how to fix that?

**Comment by Atinux** [comment]
Really sorry about this, I forgot the SPA mode 🤦 

I just releases [v1.0.3](https://github.com/nuxt-community/color-mode-module/releases/tag/v1.0.3) to fix this regression.

**Comment by nathanhenniges** [comment]
Wild thing is this still happens.

I get 'TypeError: Cannot read property 'preference' of undefined' on vercel while using the vercel-builder.

**Comment by hut-a-massmediagroup-100** [comment]
i have the same problem. please check my issue - 
https://github.com/nuxt-community/color-mode-module/issues/25
