### ISSUE TITLE
[Question] - how to you write unit tests?

### ISSUE THREAD

**Issue by Elaniobro** [nuxt-community/color-mode-module#24]
I followed the blog set-up and the color mode is working. However, any unit test I wrote, even the most basis, is failing because of the `getClasses` method in the component. 

Is there something I need to do, to set up the unit test to have the colorMode module exposed to it and or the method(s)?

**Comment by Atinux** [comment]
Hi @Elaniobro 

I think you may be able to mock the `$colorMode` object for unit testing. I don't have such experience in this field though.

**Comment by Elaniobro** [comment]
Thank you @Atinux and apologies for not closing this issue out earlier. I had done exactly as you described with mocking it up.

```js
beforeEach(() => {
  wrapper = shallowMount(ColorModePicker, {
    data() {
      return {
        colors: ['light', 'dark']
      }
    },
    mocks: {
      // adds mocked `$colorMode` object to the Vue instance
      // before mounting component
      $colorMode: {
        preference: 'dark',
        value: 'dark'
      }
    }
  })
})
```
