### ISSUE TITLE
Color-Mode appears to clash with `vue-meta` when setting `htmlAttrs` in `Nuxt.config.js`

### ISSUE THREAD

**Issue by Allezxandre** [nuxt-community/color-mode-module#26]
### Version
@nuxtjs/color-mode: v1.0.3
nuxt: v2.14.1

### Reproduction Link

I have been unable to configure CodeSandbox to use a `package.json` file.
Apologies if I am not able to provide a minimal working example,
but here's the small change required to reproduce the bug:

https://codesandbox.io/s/agitated-river-rgdqc?file=/nuxt.config.js

### Steps to reproduce

Not sure exactly how to reproduce, since I'm not too familiar with [vue-meta](https://github.com/nuxt/vue-meta), so here are the approximate steps:

- set a random `htmlAttrs` in `Nuxt.config.js`, in the `head` attribute
- use `Color-mode`
- set to dark-mode (through system or cookie)
- switch Nuxt layout **(?)** or do something that makes Nuxt reload the root HTML element (besides refreshing the page)

### What is Expected?

The `dark-mode` attribute should be present on the root HTML element

### What is actually happening?

The `dark-mode` attribute is not present, only the attributes set in `htmlAttrs` are

The [Nuxt documentation](https://nuxtjs.org/guide/views/#app-template) mentions that changing HTML attributes could be done using an `app.html` file template. Is this the way to go in place of `htmlAttrs`?

**Comment by Atinux** [comment]
Hi @Allezxandre 

Sadly, I don't think this can be easily solve, I recommend to not set any class on the html tag but instead use the `bodyAttrs` or use the `app.html` file yes.

**Comment by Allezxandre** [comment]
It's what I went with and it's been working fine this far. I'm closing this issue
