### ISSUE TITLE
TailwindCSS psuedo classes stop working after adding this

### ISSUE THREAD

**Issue by fayazara** [nuxt-community/color-mode-module#3]
I tried adding this to my nuxt project along with Tailwindcss, the dark mode selectors were working fine, but default tailwind psuedo [selectors](https://tailwindcss.com/docs/pseudo-class-variants/) like hover, focus etc  stopped working.

Any idea how to fix this?

Here is a demo -[https://github.com/fayazara/tailwind-nuxt-darkmode]( http://trite-screw.surge.sh/)
Here is the git repo - [https://github.com/fayazara/tailwind-nuxt-darkmode](https://github.com/fayazara/tailwind-nuxt-darkmode)

**Comment by bdrtsky** [comment]
Hey! 

You have this:

```js
variants: {
    backgroundColor: ['dark', 'dark-hover', 'dark-group-hover', 'dark-even', 'dark-odd'],
    borderColor: ['dark', 'dark-focus', 'dark-focus-within'],
    textColor: ['dark', 'dark-hover', 'dark-active']
},
```

While Tailwind docs says: "It's important to note that your **array of variants is not merged with the defaults**, so if you'd like to enable another variant for a utility, you need to repeat the default variants for that utility as well." https://tailwindcss.com/docs/configuring-variants/#app

Try to add `hover` states as well. Should work.

**Comment by fayazara** [comment]
Worked, thanks!
