### ISSUE TITLE
prefer color settings from cookie on iPhone

### ISSUE THREAD

**Issue by jb-alvarado** [nuxt-community/color-mode-module#38]
### Version
@nuxtjs/color-mode: v1.1.1
nuxt: 2.14.6

### Reproduction Link
Official demo [color-mode](https://color-mode.nuxtjs.app/) page.

### Steps to reproduce
On iphone with IOS 14.0.1 it don't respect the color settings from cookie.
- Open page in Firefox, Chrome, Safari and change to color to the opposed system color
- close the browser completely, also from background running
- open the browser again, with the open pages on top
- the color mode use the system color

### What is Expected?
it should always respect the settings from cookie, not only from system.

### What is actually happening?
Nuxt color-mode-module is using the the givien color as long as the browser is open, but as soon as the browser is closed and reopen it uses the system color again.

**Comment by Atinux** [comment]
Thanks for reporting, I created a PR to only use localStorage.

I tried on my iPhone and the PR fixes this issue.
