### ISSUE TITLE
Using htmlAttrs on a page breaks this module

### ISSUE THREAD

**Issue by paulpopus** [nuxt-community/color-mode-module#49]
### Version
`"@nuxtjs/color-mode": "^2.0.0"`, installed at `version: '2.0.0'`
`"nuxt": "^2.14.6"`, installed at `version: '2.14.7'`

### Reproduction Link
Here is a link to the sandbox found in the examples section, I've replaced the light page with a page that breaks it.

[Sandbox](https://codesandbox.io/s/aged-violet-8hnb2?file=/example/pages/index.vue)

Change mode to dark and then click through to that inner page, you can also inspect the markup.

### Steps to reproduce
Add the htmlAttrs to any page like so

```
head: {
    htmlAttrs: {
      class: 'test'
    }
}
```

### What is Expected?
That the light or dark class is still added to the HTML element when changing pages.

### What is actually happening?
The light or dark class is not added, only the "test" class. If the htmlAttrs is removed, then the module works again.

**Comment by TrueCarry** [comment]
@Atinux Is there a way to detect in client plugin that vue-meta is loaded and export head object in that case? I can try it, but not sure if it's possible.
