### ISSUE TITLE
Doesn't update properly

### ISSUE THREAD

**Issue by butaminas** [nuxt-community/color-mode-module#7]
I am using it to update the logo image src path based on the color mode.

It looks like this:
```
<img
        :src="$colorMode.value === 'dark' ? '/img/logo/logo-dark.svg' : '/img/logo/logo-light.svg'" />
```

If my selection is saved in cookies it works properly and displays the correct logo. But if it relies on the system preference only then it loads the logo for the light version, because the initial result of `$colorMode.value` is **system** and then it changes to **dark** (as this is my preference on Mac OS) but the logo doesn't update accordingly.

It seems that `$colorMode.value` is **system** as long as the page is still loading, after the page is fully loaded, the value is then either **light** or **dark**.

If I switch from nuxt universal mode to SPA it seems to load correctly and show the actual color mode immediately (though I'm not sure if it's because it loads faster and I can't notice it).

Any ideas?

**Comment by Atinux** [comment]
It is normal behavior since we can detect the system preference only on client side.

Wrap your image with <color-scheme> component, it will avoid the flash on client-side (see caveats section in README)
