### ISSUE TITLE
Nuxt app stuck at loading page, console throws TypeError: colorMode is undefined

### ISSUE THREAD

**Issue by vnakayama** [nuxt-community/color-mode-module#87]
I've installed the module earlier today, and it seemed to work just fine, by edditing the html class value via Firefox's dev tools. However, after trying to implement a @click="$colorMode.preference = 'dark_mode'", my app just stopped working. It gets stuck with a loading page, and the console throws _TypeError: colorMode is undefined_, it just stops if I remove '@nuxtjs/color-mode' from the nuxt.config file. I've already tried to delete de node_modules folder, reinstall the module and nothing works.

### Version
@nuxtjs/color-mode: "2.0.9"
nuxt: "2.15.6"

Apart from what I've already told above, I don't what are the steps to reproduce this error.

**Comment by vnakayama** [comment]
It also throws _Uncaught DOMException: String contains an invalid character_.

**Comment by danielroe** [comment]
@vnakayama It would be helpful to see your code even if you can't reproduce the error, if that's possible.

**Comment by vnakayama** [comment]
I hard reseted my code after the error, but the code was something like @click="$colorMode.preference = dark_mode ? 'dark' : 'light'". Manually clearing the cookies for the localhost resolved my issue, I'm terribly sorry for the confusion. I'd still like to know if this click command is somehow wrong.

**Comment by danielroe** [comment]
@vnakayama No problem at all! I just want to make sure it's not a problem in the module. If it reappears, please do ping me and we'll reopen the issue.

**Comment by vnakayama** [comment]
Will do, thank you very much for the support!
